
name: profscode_crud
description: A lightweight, GetX-friendly HTTP CRUD helper for Flutter and Dart.
version: 1.1.0
homepage: https://github.com/Ahmedhafiz33/profscode_crud
documentation: https://github.com/Ahmedhafiz33/profscode_crud#readme
repository: https://github.com/Ahmedhafiz33/profscode_crud
issue_tracker: https://github.com/Ahmedhafiz33/profscode_crud/issues

environment:
  sdk: ^3.10.4

dependencies:
  http: ^1.6.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
